description: The pipeline specialized for running DM pipeline on simulations.
instrument: lsst.obs.subaru.HyperSuprimeCam

tasks:
  detection:
    class: xlens.process_pipe.detect_multiband.DetectCoaddSourcesTask
    config:
      connections.inputCoaddName: sim_2_rot0_
      connections.outputCoaddName: sim_2_rot0_
  mergeDetections:
    class: lsst.pipe.tasks.mergeDetections.MergeDetectionsTask
    config:
      connections.inputCoaddName: sim_2_rot0_
      connections.outputCoaddName: sim_2_rot0_
  deblend:
    class: lsst.pipe.tasks.deblendCoaddSourcesPipeline.DeblendCoaddSourcesMultiTask
    config:
      connections.inputCoaddName: sim_2_rot0_
      connections.outputCoaddName: sim_2_rot0_
  measure:
    class: xlens.process_pipe.measure_multiband.MeasureMergedCoaddSourcesTask
    config:
      connections.inputCoaddName: sim_2_rot0_
      connections.outputCoaddName: sim_2_rot0_
      python: |
        config.measurement.plugins["base_PixelFlags"].masksFpCenter.remove("BRIGHT_OBJECT")
        config.measurement.plugins["base_PixelFlags"].masksFpAnywhere.remove("BRIGHT_OBJECT")
        config.measurement.plugins.names.remove("base_InputCount")
        config.measurement.plugins.names.remove("subaru_FilterFraction")
        config.measurement.plugins["base_CircularApertureFlux"].radii = [3.0, 4.5, 6.0, 9.0, 12.0]
  # mergeMeasurements:
  #   class: lsst.pipe.tasks.mergeMeasurements.MergeMeasurementsTask
  #   config:
  #     connections.inputCoaddName: sim_2_rot0_
  #     connections.outputCoaddName: sim_2_rot0_
  # force:
  #   class: xlens.process_pipe.force_multiband.ForcedPhotCoaddTask
  #   config:
  #     connections.inputCoaddName: sim_2_rot0_
  #     connections.outputCoaddName: sim_2_rot0_
  #     python: |
  #       config.measurement.plugins["base_PixelFlags"].masksFpCenter.remove("BRIGHT_OBJECT")
  #       config.measurement.plugins["base_PixelFlags"].masksFpAnywhere.remove("BRIGHT_OBJECT")
  #       config.measurement.plugins["base_CircularApertureFlux"].radii = [3.0, 4.5, 6.0, 9.0, 12.0]
  #       config.doApCorr = False
  # transformObjectTable:
  #   class: lsst.pipe.tasks.postprocess.TransformObjectCatalogTask
  #   config:
  #     connections.coaddName: sim_2_rot0_
  # writeObjectTable:
  #   class: lsst.pipe.tasks.postprocess.WriteObjectTableTask
  #   config:
  #     connections.coaddName: sim_2_rot0_
