description: The pipeline specialized for testing image simulation.
instrument: lsst.obs.subaru.HyperSuprimeCam

tasks:
  MutibandSim1:
    class: xlens.sim_pipe.multibandSim.MultibandSimShearPipe
    config:
      simulator.survey_name: hsc
      simulator.mode: 0
      simulator.rotId: 0
      connections.mode: 0
      connections.rotId: 0

  MutibandSim2:
    class: xlens.sim_pipe.multibandSim.MultibandSimShearPipe
    config:
      simulator.survey_name: hsc
      simulator.mode: 0
      simulator.rotId: 1
      connections.mode: 0
      connections.rotId: 1

  MutibandSim3:
    class: xlens.sim_pipe.multibandSim.MultibandSimShearPipe
    config:
      simulator.survey_name: hsc
      simulator.mode: 1
      simulator.rotId: 0
      connections.mode: 1
      connections.rotId: 0

  MutibandSim4:
    class: xlens.sim_pipe.multibandSim.MultibandSimShearPipe
    config:
      simulator.survey_name: hsc
      simulator.mode: 1
      simulator.rotId: 1
      connections.mode: 1
      connections.rotId: 1

  DetectTask1:
    class: xlens.process_pipe.fpfs_joint.FpfsJointPipe
    config:
      do_dm_detection: False
      fpfs.use_average_psf: True
      fpfs.do_noise_bias_correction: False
      connections.coaddName: sim_0_rot0_

  DetectTask2:
    class: xlens.process_pipe.fpfs_joint.FpfsJointPipe
    config:
      do_dm_detection: False
      fpfs.use_average_psf: True
      fpfs.do_noise_bias_correction: False
      connections.coaddName: sim_0_rot1_

  DetectTask3:
    class: xlens.process_pipe.fpfs_joint.FpfsJointPipe
    config:
      do_dm_detection: False
      fpfs.use_average_psf: True
      fpfs.do_noise_bias_correction: False
      connections.coaddName: sim_1_rot0_

  DetectTask4:
    class: xlens.process_pipe.fpfs_joint.FpfsJointPipe
    config:
      do_dm_detection: False
      fpfs.use_average_psf: True
      fpfs.do_noise_bias_correction: False
      connections.coaddName: sim_1_rot1_

  ForceTask1:
    class: xlens.process_pipe.fpfs_force.FpfsForcePipe
    config:
      fpfs.sigma_arcsec1: 0.52
      fpfs.use_average_psf: True
      fpfs.do_noise_bias_correction: False
      connections.coaddName: sim_0_rot0_

  ForceTask2:
    class: xlens.process_pipe.fpfs_force.FpfsForcePipe
    config:
      fpfs.sigma_arcsec1: 0.52
      fpfs.use_average_psf: True
      fpfs.do_noise_bias_correction: False
      connections.coaddName: sim_0_rot1_

  ForceTask3:
    class: xlens.process_pipe.fpfs_force.FpfsForcePipe
    config:
      fpfs.sigma_arcsec1: 0.52
      fpfs.use_average_psf: True
      fpfs.do_noise_bias_correction: False
      connections.coaddName: sim_1_rot0_

  ForceTask4:
    class: xlens.process_pipe.fpfs_force.FpfsForcePipe
    config:
      fpfs.sigma_arcsec1: 0.52
      fpfs.use_average_psf: True
      fpfs.do_noise_bias_correction: False
      connections.coaddName: sim_1_rot1_

  SelectBiasTask:
    class: xlens.summary_pipe.selbias_m00_multiband.SelBiasMultibandPipe
    config:
      shape_name: "i_fpfs1_e1"
      m00_name: "i_fpfs1_m00"
      do_correct_selection_bias: True
      connections.dataType: force
      connections.coaddName: sim

  Summary:
    class: xlens.summary_pipe.selbias_m00_multiband.SelBiasSummaryMultibandPipe
    config:
      connections.dataType: force
      connections.coaddName: sim

  # SelectBiasTaskRanforest:
  #   class: xlens.summary_pipe.selbias_ranforest_multiband.SelBiasRfMultibandPipe
  #   config:
  #     shape_name: "i_fpfs1_e1"
  #     do_correct_selection_bias: True
  #     mag_zero: 27.0
  #     connections.dataType: force
  #     connections.coaddName: sim
  #     model_name: simple_sim_RF.pkl  # need to use absolute dir if run with bps

  # SummaryRanForest:
  #   class: xlens.summary_pipe.selbias_ranforest_multiband.SelBiasRfSummaryMultibandPipe
  #   config:
  #     connections.dataType: force
  #     connections.coaddName: sim
