description: The pipeline specialized for testing image simulation.
instrument: lsst.obs.subaru.HyperSuprimeCam

tasks:
  MutibandSim1:
    class: xlens.sim_pipe.multibandSim.MultibandSimShearPipe
    config:
      simulator.draw_image_noise: True
      simulator.layout: hex
      simulator.survey_name: hsc
      simulator.galaxy_type: WLDeblend
      simulator.mode: 2
      simulator.rotId: 0
      simulator.use_real_psf: True
      connections.mode: 2
      connections.rotId: 0
