description: The pipeline specialized for testing image simulation.
instrument: lsst.obs.lsst.LsstCam

tasks:
  MutibandSimHalo1:
    class: xlens.sim_pipe.halo_multiband.MultibandSimHaloPipe
    config:
      connections.psfType: moffat
      connections.simType: _test_halo
      connections.mode: 0
      connections.irot: 0
      simulator.mass: 8e14
      simulator.z_lens: 0.25
      simulator.ra_lens: 0.0  # arcsec
      simulator.dec_lens: 0.0 # arcsec
      simulator.z_source: 1.0
      simulator.survey_name: lsst

  MutibandSimHalo2:
    class: xlens.sim_pipe.halo_multiband.MultibandSimHaloPipe
    config:
      connections.psfType: moffat
      connections.simType: _test_halo
      connections.mode: 0
      connections.irot: 1
      simulator.mass: 8e14
      simulator.z_lens: 0.25
      simulator.ra_lens: 0.0  # arcsec
      simulator.dec_lens: 0.0 # arcsec
      simulator.z_source: 1.0
      simulator.survey_name: lsst

  FpfsTask1:
    class: xlens.process_pipe.fpfs_multiband.FpfsMultibandPipe
    config:
      do_dm_detection: False
      fpfs.use_average_psf: True
      fpfs.do_adding_noise: False
      connections.dataType: _test_halo_0_rot0
      
  FpfsTask2:
    class: xlens.process_pipe.fpfs_multiband.FpfsMultibandPipe
    config:
      do_dm_detection: False
      fpfs.use_average_psf: True
      fpfs.do_adding_noise: False
      connections.dataType: _test_halo_0_rot1

  SummaryTask:
    class: xlens.summary_pipe.halo_mcbias_multiband.HaloMcBiasMultibandPipe
    config:
      connections.dataType: _test_halo
      mass: 8e14
      z_lens: 0.25
      z_source: 1.0