description: The pipeline specialized for testing image simulation.
instrument: lsst.obs.lsst.LsstCam

tasks:
  DetectionTask1:
    class: xlens.process_pipe.jointdetect.JointDetectPipe
    config:
      fpfs.use_average_psf: True
      fpfs.do_adding_noise: False
      connections.dataType: _test_0_rot0

  DetectionTask2:
    class: xlens.process_pipe.jointdetect.JointDetectPipe
    config:
      fpfs.use_average_psf: True
      fpfs.do_adding_noise: False
      connections.dataType: _test_0_rot1

  DetectionTask3:
    class: xlens.process_pipe.jointdetect.JointDetectPipe
    config:
      fpfs.use_average_psf: True
      fpfs.do_adding_noise: False
      connections.dataType: _test_1_rot0

  DetectionTask4:
    class: xlens.process_pipe.jointdetect.JointDetectPipe
    config:
      fpfs.use_average_psf: True
      fpfs.do_adding_noise: False
      connections.dataType: _test_1_rot1

  FpfsTask1:
    class: xlens.process_pipe.fpfs_multiband.FpfsMultibandPipe
    config:
      fpfs.use_average_psf: True
      fpfs.do_adding_noise: False
      connections.dataType: _test_0_rot0

  FpfsTask2:
    class: xlens.process_pipe.fpfs_multiband.FpfsMultibandPipe
    config:
      fpfs.use_average_psf: True
      fpfs.do_adding_noise: False
      connections.dataType: _test_0_rot1

  FpfsTask3:
    class: xlens.process_pipe.fpfs_multiband.FpfsMultibandPipe
    config:
      fpfs.use_average_psf: True
      fpfs.do_adding_noise: False
      connections.dataType: _test_1_rot0

  FpfsTask4:
    class: xlens.process_pipe.fpfs_multiband.FpfsMultibandPipe
    config:
      fpfs.use_average_psf: True
      fpfs.do_adding_noise: False
      connections.dataType: _test_1_rot1

  SummaryTask:
    class: xlens.summary_pipe.mcbias_multiband.McBiasMultibandPipe
    config:
      connections.dataType: _test
